# Generated by Django 3.0.5 on 2020-04-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('tipo_consulta', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Citas',
                'db_table': 'Cita',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'db_table': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_empleado', models.CharField(max_length=50)),
                ('apellidos_empleado', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('pulso', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('presion_arterial', models.CharField(max_length=3)),
                ('nombre_refiere', models.CharField(max_length=50)),
                ('enfermedades_preexistentes', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=50)),
                ('medicamentos_actuales', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=50)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='appClinica.Cita')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='appClinica.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Expedientes',
                'db_table': 'Expediente',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('id_consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.CASCADE, to='appClinica.Consulta')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='appClinica.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Recetas',
                'db_table': 'Receta',
            },
        ),
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id_radiografia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_radiografia', models.CharField(max_length=50)),
                ('imagen_radiografia', models.CharField(max_length=50)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, to='appClinica.Expediente')),
            ],
            options={
                'verbose_name_plural': 'Radiografias',
                'db_table': 'Radiografia',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='appClinica.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='appClinica.Empleado'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_expediente',
            field=models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.DO_NOTHING, to='appClinica.Expediente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='appClinica.Paciente'),
        ),
    ]
